---
title: "Project Overview"
author: "Jesse Brodrick"
date: "2024-03-12"
output: 
  html_document:
    fig_caption: no
    number_sections: no
    toc: no
    toc_float: false
    collapsed: no
---

# Forest Monitoring: A Comprehensive Analysis of Forest Cover and Carbon Emissions over 20 years within the Pacific Northwest 

## GSW tools, History, and Project Overview

#### In recent decades, the urgency to understand and monitor our planet's forests has spurred significant advancements in remote sensing and data analysis techniques. Global Forest Watch (GFW), an initiative since 2014, has been at the forefront of providing accessible data on forests worldwide. Groundbreaking datasets like the Tree Canopy Cover, introduced by the University of Maryland’s (UMD) GLAD Lab in 2013, have allowed researchers to analyze forest coverage at global scale using a medium resolution of 30-meters. This data set marked a pivotal contribution of establishing a baseline for the annual. Within this data set, tree canopy cover is defined as the density of foliage above five meters in height within a given pixel, measured from the dependable Landsat series of satellites.

#### Following this trajectory, the UMD GLAD Lab introduced the Tree Cover Height dataset in 2021, revealing not just the density of tree cover but also the vertical dimension as well with the partnership of Global Ecosystem Dynamics Investigation (GEDI) LiDAR measurements. This data set is distinguished by its precision estimating tree height changes which aids the accurate assessment of forest biomass and carbon storage because of their linear relation. 

#### It is also important to note that the data set that this project uses, defines trees as woody vegetation of at least three meters in height and is estimated by the height of the tree canopy in meters within a 30-meter pixel from Global GEDI LiDAR measurements and Landsat imagery. This data set estimates the 95th percentile of tree canopy height, and accordingly will represent the upper bounds of height for pixels with fractional tree cover, or pixels with variable canopy height. Afterwards, the data is aggregated and vectorized into sub-national polygons. Thus, this data may take the form of natural forests or plantations across a range of canopy densities. “Loss” indicates the removal or mortality of tree cover and can be due to a variety of factors, including mechanical harvesting, fire, disease, or storm damage.

## Project Objectives: 

#### This project builds on the foundation laid by the GFW datasets, with the aim to deliver a detailed analysis of county level primary forest cover dynamics, particularly focusing on gain and loss patterns across the United States. Utilizing the 20-year net change data from GFW, this study employs a suite of data science techniques in RStudio to map, quantify, and compare forest changes.

## Methods: 

#### The materials consist of a GFW dataset on a subnational2 county level for tree cover change and C02 emissions . Several packages including (-tidyverse, -sf, -ggplot2,- RColorBrewer,-tigris, -ggplot2, -classInt, -spdep...).  

#### Global Forest watch provides thresholds or amount of tree canopy coverage for 0, 10, 20, 30, 50, and 75 percent for 20 years of forest cover gain/loss in hecatares. In order to stay consistent, as well complete a valid spatial join I used 50% threshold of very dense forest (VDF) and, moderately dense forests (MDF) in which I joined by state and county to Census Boundaries from the TIGRIS package. 


### Assessment of Spatiotemporal Distribution and Variability of Forest Cover:

#### Within this project, the tree cover gain and loss pages provide you with maps using GGpot package to illustrate the fluctuations in forest cover, offering a visual narrative and an overall trend analysis to visualize arboreal gains and losses at the county level since the year 2000. The maps serve as a starting point and basis for additional analyses into the causes and consequences of forest cover changes. I have also generated standard deviation maps that highlight the variability and intensity of changes denoting the amount of gain compared county to county within the 20 year time-span. This can be used as a tool to provide insights into the regions most affected by deforestation or reforestation practices. 

### Spatial Autocorrelation with Moran's I:

#### This project also provides Local and Global Moran’s I analyses to classify clustering, dispersion, or randomness. This approach is also supplemented by a Monte Carlo simulation to assess how “typical” or “atypical” the data may be relative to a randomly distributed pattern of gain and loss across the counties. Along with that, I provided hot zone (High-High) and cold zone (Low-Low) maps which depict neighboring counties that are statistically significant or in the <.05 p-value range. In summary, Moran's I provides a quantitative measure of how forest gain and loss are distributed across a landscape, offering insights that can inform management decisions, policy development, and conservation strategies. It is a valuable tool in the spatial analysis of forest dynamics, helping to ensure that forest resources are managed sustainably and that biodiversity is preserved. 


### Carbon Dynamics

#### The project also contains a regression analysis to discern the correlation CO2 emissions and forest cover loss within the PNW compared to the United Sates . Furthermore, a time-series regression for looking at basic projections on the trajectory of forest growth/decline rate in the PNW. This analysis is important for understanding the interaction between human activities and natural processes, providing a basis for informed decision-making and strategic planning in environmental conservation and climate change mitigation efforts.


#### Through data manipulation and statistical modeling, this project strives to offer a multifaceted view of forest dynamics, underpinning conservation efforts and policy-making with quantitative evidence and predictive insights. With   the current state of the world where our forest are being overused by human activity and burned by climate change induced fires, the need for such data-driven studies becomes ever more critical.

### Discussion on Standard Deviation Forest Cover Gain Maps:

#### The categorization of tree cover gain based on the mean and standard deviation, with the constraints of using 4 colors, translates the statistical data into a more intuitive understanding of how tree cover gain varies across different areas. They include:

#### Below Average: Areas falling into this category have gained significantly less tree cover than the average area. This might indicate regions where reforestation efforts are less successful, areas that have experienced recent deforestation that hasn't been countered by new growth, or simply areas where natural tree cover gain is slower.

#### Average: These areas have tree cover gains close to the mean of the dataset. This suggests that tree cover gain here is typical or expected, based on the overall data. It represents a baseline against which other areas can be compared.

#### Above Average: Areas in this category have gained more tree cover than average but not to an extreme degree. This could be indicative of successful reforestation efforts, natural recovery from previous deforestation, or areas benefiting from favorable environmental conditions promoting tree growth.

#### Exceptionally High: This category represents areas with significantly higher tree cover gain than most other areas. Such exceptional gains might be due to intensive reforestation projects, areas recovering from large-scale disturbances (like fires or clear-cutting), or possibly errors in data (always a consideration in data analysis).

### Interpretation and Actions:

#### Research and Investigation: Exceptional cases, both low and high, can be subjects for further investigation to understand the factors contributing to their performance. This might include climate conditions, soil fertility, human intervention, and more.

#### Targeted Efforts: Resources for tree planting, conservation, and habitat restoration can be directed more effectively when areas are categorized by their tree cover gain. Regions with Below Average gains might be prioritized for new projects, while the strategies used in Exceptionally High gain areas could be studied and replicated elsewhere.


## Limitations:

#### Improved satellite data: The algorithm uses every available Landsat image (from the Landsat 5, 7 and, since 2013, Landsat 8 satellites) to detect tree cover loss. The Landsat 8 satellite has the same resolution as previous Landsat missions, but has an improved sensor that can better resolve features on the ground. Incorporation of Landsat 8 data into the loss algorithm resulted in better detections of tree cover loss smaller than an individual pixel (e.g. selective logging) starting in 2013.

#### Algorithm adjustments: The original algorithm used to map tree cover loss from satellite images for 2001-2012 has been improved upon in subsequent updates. These improvements allowed for annual updates starting in 2013 (coupled with small additions to the 2011 and 2012 data) and have resulted in enhanced detection of loss— particularly from 2015 onwards.

#### Tree cover gain is more difficult to measure than loss: Whereas tree cover loss is distinctly visible at a specific moment in time, tree cover gain is a gradual process and is thus more difficult to discern from one satellite image to the next. Annual reporting of tree cover loss has not been matched by annual reporting of tree cover gain, resulting in an unbalanced view of global forest change dynamics.

#### Tree cover loss and gain do not equal net forest. Due to variation in research methodology and rate in which gains occur versus loss, tree cover, tree cover loss, and tree cover gain data sets cannot be compared accurately against each other. Accordingly, “net” loss cannot be calculated by subtracting figures for tree cover gain from tree cover loss, and current (post-2000) tree cover cannot be determined by subtracting figures for annual tree cover loss from year 2000 tree cover.



## Conclusion:

#### When first looking at our data of our gain and loss maps the patterns observed in the counties with both high tree cover loss and gain over the past 20 years may reflect a dynamic landscape where reforestation and deforestation occur simultaneously or in close succession. This could be due to a variety of factors, including forestry practices like clear-cutting followed by replanting, natural disturbances followed by recovery, or changes in land use where areas are alternately being deforested for development and other areas being reforested for conservation. These findings suggest a complex interplay between conservation efforts, land management strategies, and economic development, highlighting the need for a sustainable approach to forestry that balances ecological health with human needs.


#### Within the local Morans I of identifying local clusters and local spatial outliers using row-standardized weights w proved that these patterns are not random and indicate that there might be underlying factors—such as environmental conditions, land use policies, or economic activities—contributing to these clustered patterns of forest cover change. This can be useful for a future multivariate analysis. For example, if deforestation is occurring primarily in specific regions due to human activities or natural causes, Moran's I can help identify these hotspots.

#### When expanding past this analysis, there are a multitude of underlying varaibles that can be assesed. For instance,  this can be used for guiding conservation efforts by our identified areas of significant forest change Policymakers and conservationists can target interventions more effectively. therefore, they can focus reforestation efforts in regions where loss is clustered or protect areas of significant gain. One other example is understanding ecological Processes: Forest ecology is inherently spatial. Processes like seed dispersal, wildfire spread, and disease outbreaks all exhibit spatial patterns. Moran's I helps understand these processes by identifying patterns that may indicate ecological interactions which is related to landscape connectivity: In conservation biology, landscape connectivity is crucial for maintaining biodiversity. Moran's I can indicate the degree to which forested areas or how in this project, counties are fragmented and connected. This also has implications for predicting carbon dioxide emission gain over time we could see in our hot zone clustered areas and how we should take note of what the cold zone clustered areas are doing to follow suit.

#### The inclusion of regression analysis in this project to discern the correlation between CO2 emissions and forest cover loss, both within the Pacific Northwest (PNW) and across the United States, is significant for several reasons: Understanding Environmental Impacts: CO2 emissions are a major driver of climate change, and forests play a critical role in carbon sequestration. Analyzing the relationship between emissions and forest cover loss reveals how changes in forest areas may be contributing or to or mitigating climate change.

#### Additionally, by comparing the PNW with the entire United States, the analysis highlighted regional differences in the relationship between emissions and forest changes. This lead to a more nuanced understanding of how the the correlation between CO2 and tree cover loss was way stronger than the overall US. This could be due to local factors—such as clear cutting from a large timber economy in the PNW, wildfires which also influence CO2 emissions.


#### This project, using Global Forest Watch data and R, reveals a nuanced understanding of forest cover dynamics over the past two decades. Through the analysis, it highlighted not just the areas of tree cover gain and loss, but also the spatial distribution patterns—showing significant clustering rather than randomness in these changes. This suggests that environmental policies, land management practices, and other regional factors are likely influencing these patterns. The positive correlation between CO2 emissions and tree cover loss in the US, particularly within the Pacific Northwest, underscores the interconnectedness of human activities and forest changes. Overall, this work contributes valuable insights into forest conservation efforts, highlighting areas that may require more focused intervention to manage and mitigate the impact of anthropogenic activities on forest ecosystems.












